### ISSUE TITLE
please check chainId mismatch warning

### ISSUE THREAD

**Issue by yepp4you** [EOSEssentials/Scatter#87]
If you use eosjs in scatter, be sure to check if you do not include the chainId value.
eosjs code 
https://github.com/EOSIO/eosjs/blob/master/src/index.js#L80

warning
index.js:387 WARN: chainId mismatch, signatures will not match transaction authority. expected cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f !== actual aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906
(anonymous) @ index.js:387
run @ es6.promise.js:75
(anonymous) @ es6.promise.js:92
flush @ _microtask.js:18
characterData (async)
notify @ _microtask.js:39
(anonymous) @ _microtask.js:66
notify @ es6.promise.js:56
$resolve @ es6.promise.js:162
(anonymous) @ _ctx.js:8
callback @ process-args.js:74
callback @ apigen.js:99
(anonymous) @ apigen.js:126
Promise.then (async)
(anonymous) @ apigen.js:121
checkChainId @ index.js:385
createEos @ index.js:79
Eos @ index.js:34
Promise.all.t.transaction.actions.map @ inject.js:34
_ @ inject.js:34
f @ inject.js:34
_callee2$ @ write-api.js:635
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
tryCatch @ runtime.js:65
invoke @ runtime.js:155
(anonymous) @ runtime.js:202
Promise @ es6.promise.js:177
callInvokeWithMethodAndArg @ runtime.js:201
enqueue @ runtime.js:224
prototype.(anonymous function) @ runtime.js:117
./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js.runtime.async @ runtime.js:248
_callee2 @ write-api.js:593
(anonymous) @ write-api.js:787
(anonymous) @ exported-helpers.js:68
(anonymous) @ exported-helpers.js:78
callback @ process-args.js:65
callback @ apigen.js:99
(anonymous) @ apigen.js:126
Promise.then (async)
(anonymous) @ apigen.js:121
(anonymous) @ exported-helpers.js:51
(anonymous) @ exported-helpers.js:78
callback @ process-args.js:65
callback @ apigen.js:99
(anonymous) @ apigen.js:126
Promise.then (async)
(anonymous) @ apigen.js:121
createTransaction @ exported-helpers.js:48
api.(anonymous function) @ apigen.js:46
transaction @ write-api.js:591
_callee$ @ write-api.js:294
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
tryCatch @ runtime.js:65
invoke @ runtime.js:155
(anonymous) @ runtime.js:165
run @ es6.promise.js:75
(anonymous) @ es6.promise.js:92
flush @ _microtask.js:18
characterData (async)
notify @ _microtask.js:39
(anonymous) @ _microtask.js:66
notify @ es6.promise.js:56
$resolve @ es6.promise.js:162
(anonymous) @ _ctx.js:8
callback @ process-args.js:74
callback @ apigen.js:99
(anonymous) @ apigen.js:126
Promise.then (async)
(anonymous) @ apigen.js:121
abiAsync @ abi-cache.js:25
genContractActions @ write-api.js:311
merge.contract @ write-api.js:74
Promise @ inject.js:34
Promise @ es6.promise.js:177
n @ inject.js:34
voteApi @ eos.js:242
runCallEffect @ proc.js:513
runEffect @ proc.js:435
next @ proc.js:315
currCb @ proc.js:388
(anonymous) @ proc.js:499
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
(anonymous) @ middleware.js:22
(anonymous) @ index.js:55
(anonymous) @ redux.js:449
handleVote @ Vote.js:94
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:461
executeDispatchesInOrder @ react-dom.development.js:483
executeDispatchesAndRelease @ react-dom.development.js:581
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:592
forEachAccumulated @ react-dom.development.js:562
runEventsInBatch @ react-dom.development.js:723
runExtractedEventsInBatch @ react-dom.development.js:732
handleTopLevel @ react-dom.development.js:4472
batchedUpdates$1 @ react-dom.development.js:16537
batchedUpdates @ react-dom.development.js:2131
dispatchEvent @ react-dom.development.js:4551
interactiveUpdates$1 @ react-dom.development.js:16592
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4528
inject.js:34 protocol https

**Comment by nsjames** [comment]
Are you seeing this from your dapp, or is it bubbling up to the dapp from Scatter?

**Comment by eoseoul** [comment]
It has been fixed in scatter@6.0.4.
Thank you.

**Comment by nsjames** [comment]
<3

**Comment by gustavomick** [comment]
@nsjames we still have this issue on 6.0.4 , let me know if i need to do something differently. thanks.

![image](https://user-images.githubusercontent.com/4327429/41553813-44d94996-7309-11e8-8472-37242d1d480c.png)
![image](https://user-images.githubusercontent.com/4327429/41553827-4be44bd2-7309-11e8-82c1-3917e1926170.png)

**Comment by nsjames** [comment]
pass chainId into the options parameter of `scatter.eos(...,{chainId})`
